steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '-t', 'europe-central2-docker.pkg.dev/cultureua/culture-ua/culture-ua-ui-dev', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-central2-docker.pkg.dev/cultureua/culture-ua/culture-ua-ui-dev']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'services', 'update', 'culture-ua-ui-dev', '--platform=managed', '--image=europe-central2-docker.pkg.dev/cultureua/culture-ua/culture-ua-ui-dev:latest', '--region=europe-central2', '--quiet']
timeout: 1200s
options:
 machineType: 'E2_HIGHCPU_8'