/**
 * ua.culture.monuments.api.v1.TripApi
 * Auth Service
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ermakovsa03@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ArticleDTO {
    id?: string;
    url?: string;
    name?: string;
    author?: string;
    language?: string;
    numberOfViews?: number;
    previewImageUrl?: string;
    creationDate?: Date;
    article?: string;
}

export interface ArticleListDTO {
    pageSize?: number;
    pageNumber?: number;
    numberOfArticles?: number;
    articles?: Array<ArticleDTO>;
}

export interface Base64FileDTO {
    base64?: string;
}

export interface CoordinatesDTO {
    lat?: number;
    lon?: number;
}

export interface EmailDTO {
    email?: string;
    language?: string;
}
/**
 * @export
 * @enum {string}
 */
export enum HelpTypeDTO {
    VOLUNTEER = "VOLUNTEER",
    PUBLICORGANISATIONMEMBER = "PUBLIC_ORGANISATION_MEMBER",
    ARCHITECT = "ARCHITECT",
    OTHER = "OTHER",
}

export interface MonumentDTO {
    id?: string;
    name?: string;
    address?: string;
    description?: string;
    constructionDate?: string;
    destructionDate?: string;
    type?: MonumentTypeDTO;
    status?: MonumentStatusDTO;
    level?: MonumentLevelDTO;
    ownership?: MonumentOwnershipDTO;
    coordinates?: CoordinatesDTO;
    photos?: Array<PhotoDTO>;
}
/**
 * @export
 * @enum {string}
 */
export enum MonumentLevelDTO {
    NATIONAL = "NATIONAL",
    LOCAL = "LOCAL",
    NOREGISTER = "NO_REGISTER",
}

export interface MonumentListDTO {
    monuments?: Array<MonumentDTO>;
}
/**
 * @export
 * @enum {string}
 */
export enum MonumentOwnershipDTO {
    PRIVATE = "PRIVATE",
    COMUN = "COMUN",
    CONCESSION = "CONCESSION",
}
/**
 * @export
 * @enum {string}
 */
export enum MonumentStatusDTO {
    COMPLETELYDESTROYED = "COMPLETELY_DESTROYED",
    PARTIALLYDESTROYED = "PARTIALLY_DESTROYED",
    DAMAGED = "DAMAGED",
}
/**
 * @export
 * @enum {string}
 */
export enum MonumentTypeDTO {
    CHURCH = "CHURCH",
    COSTEL = "COSTEL",
    MUSEUM = "MUSEUM",
    LIBRARY = "LIBRARY",
    UNIVERSITY = "UNIVERSITY",
    THEATRE = "THEATRE",
    MONUMENT = "MONUMENT",
    OLDBUILDING = "OLD_BUILDING",
    ADMINISTRATIVEBUILDING = "ADMINISTRATIVE_BUILDING",
}

export interface PersonHelpDTO {
    name?: string;
    address?: string;
    contactInformation?: string;
    comment?: string;
    type?: HelpTypeDTO;
}

export interface PhotoDTO {
    id?: string;
    monumentId?: string;
    reportedMonumentId?: string;
    publicFileUrl?: string;
    originalFileName?: string;
    createdAt?: number;
}

export interface ReportedMonumentDTO {
    id?: string;
    name?: string;
    address?: string;
    destructionDate?: string;
    contactInformation?: string;
    photos?: Array<PhotoDTO>;
}
